# Generated by Django 3.1.1 on 2020-12-16 20:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('business', '0001_initial'),
        ('institution', '0007_auto_20201210_1625'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(max_length=128)),
                ('reason', models.TextField(blank=True, max_length=256, null=True)),
                ('transaction_code', models.CharField(max_length=256)),
                ('term_of_loan', models.CharField(max_length=128, null=True)),
                ('date_of_payment', models.DateField(max_length=128, null=True)),
                ('business_number', models.CharField(max_length=128)),
                ('loan_status', models.CharField(default='UNPAID', max_length=128)),
                ('business_certificate', models.ImageField(upload_to='businessDocument/')),
                ('is_deleted', models.BooleanField(default=False)),
                ('date_created', models.DateField(auto_now=True)),
                ('date_time_created', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_loan', to='business.business')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='institution_loan', to='institution.institution')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_loan', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
