# Generated by Django 3.1.1 on 2020-12-18 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='institution_action_by',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='loan',
            name='loan_category',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
