# Generated by Django 3.1.1 on 2020-12-18 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0002_auto_20201218_1305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='loan_category',
            field=models.CharField(default='PENDING', max_length=128),
        ),
    ]
