# Generated by Django 3.1.1 on 2020-12-19 20:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('business', '0002_businesscustommetric'),
        ('institution', '0007_auto_20201210_1625'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportMetric',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateField(auto_now=True)),
                ('date_time_created', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='business_report_metric', to='business.business')),
                ('business_custom_metric', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='business_custom_report_metric', to='business.businesscustommetric')),
                ('institution', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='institution_report_metric', to='institution.institution')),
                ('institution_custom_metric', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='institution_custom_report_metric', to='institution.institutioncustommetric')),
            ],
        ),
    ]
