# Generated by Django 3.1.1 on 2020-12-20 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businessreport', '0003_auto_20201219_2316'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportmetric',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
