# Generated by Django 3.1.1 on 2020-12-20 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businessreport', '0004_reportmetric_is_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthreport',
            name='report_code',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
