# Generated by Django 3.1.1 on 2020-12-24 22:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('institution', '0007_auto_20201210_1625'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('business', '0002_businesscustommetric'),
        ('businessreport', '0006_auto_20201220_0105'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthReportSummary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_category', models.CharField(max_length=256, null=True)),
                ('reporting_date', models.DateField()),
                ('is_deleted', models.BooleanField(default=False)),
                ('date_created', models.DateField(auto_now=True)),
                ('date_time_created', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_month_report_summary', to='business.business')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='institution_month_report_summary', to='institution.institution')),
                ('report_metric', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_metric_summary', to='businessreport.reportmetric')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_month_report_summary', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='monthreport',
            name='month_report_summary',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='month_report_summary', to='businessreport.monthreportsummary'),
        ),
    ]
