# Generated by Django 3.1.1 on 2020-12-24 23:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('businessreport', '0007_auto_20201224_2240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthreportsummary',
            name='report_metric',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='report_metric_summary', to='businessreport.reportmetric'),
        ),
    ]
