# Generated by Django 3.1.1 on 2020-12-11 22:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('slug', models.SlugField(blank=True, max_length=250, null=True)),
                ('contact', models.CharField(max_length=128, null=True)),
                ('location', models.CharField(max_length=128)),
                ('district', models.CharField(max_length=128)),
                ('region', models.CharField(max_length=128)),
                ('country', models.CharField(max_length=128)),
                ('industry', models.CharField(max_length=128)),
                ('tagline', models.TextField(default='Tagline')),
                ('mission', models.TextField(null=True)),
                ('vision', models.TextField(null=True)),
                ('about', models.TextField(null=True)),
                ('website', models.TextField(null=True)),
                ('competitors', models.TextField(null=True)),
                ('product_description', models.TextField(null=True)),
                ('market_description', models.TextField(null=True)),
                ('date_of_coperation', models.DateField()),
                ('founder', models.CharField(max_length=128, null=True)),
                ('logo', models.ImageField(upload_to='businessLogo/')),
                ('is_deleted', models.BooleanField(default=False)),
                ('date_created', models.DateField(auto_now=True)),
                ('date_time_created', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_business', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
