# Generated by Django 3.1.1 on 2020-12-03 11:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('contact', models.CharField(max_length=128)),
                ('location', models.CharField(max_length=128)),
                ('district', models.CharField(max_length=128)),
                ('region', models.CharField(max_length=128)),
                ('country', models.CharField(max_length=128)),
                ('logo', models.FileField(upload_to='institutionLogo/')),
                ('is_deleted', models.BooleanField(default=False)),
                ('date_created', models.DateField(auto_now=True)),
                ('date_time_created', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_institution', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
