# Generated by Django 3.1.1 on 2020-12-03 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institution', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institution',
            name='logo',
            field=models.ImageField(upload_to='institutionLogo/'),
        ),
    ]
