# Generated by Django 3.1.1 on 2020-12-05 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institution', '0002_auto_20201203_2132'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='founder',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='institution',
            name='mission',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='institution',
            name='tagline',
            field=models.TextField(default='Tagline'),
        ),
        migrations.AddField(
            model_name='institution',
            name='vision',
            field=models.TextField(null=True),
        ),
    ]
