# Generated by Django 3.1.1 on 2020-12-05 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institution', '0003_auto_20201205_0307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institution',
            name='contact',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
