# Generated by Django 3.1.1 on 2020-12-10 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institution', '0005_institutioncustommetric'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institutioncustommetric',
            name='description',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='institutioncustommetric',
            name='metric_short_name',
            field=models.CharField(default='msn', max_length=128),
        ),
    ]
