# Generated by Django 3.1.1 on 2020-12-10 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institution', '0006_auto_20201210_1325'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='slug',
            field=models.SlugField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='institutioncustommetric',
            name='slug',
            field=models.SlugField(blank=True, max_length=250, null=True),
        ),
    ]
